version: '3'

services:
  payments:
    build: ../
    restart: always
    depends_on:
      - postgres
    ports:
      - 80:8080
    env_file:
      - db.env

  postgres:
    build: ./postgres
    restart: always
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
